- name: Gerar arquivo de configuração
  hosts: all
  become: yes
  tasks:
    - name: Criar arquivo de configuração com template
      ansible.builtin.template:
        src: templates/config.j2
        dest: /etc/myconfig.conf
        owner: root
        group: root
        mode: '0644'
